import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import * as request from 'supertest';
import { Reflector } from '@nestjs/core';
import { AppModule } from './../src/app.module';
import { PrismaService } from './../src/common/prisma/prisma.service';
import { AiService } from './../src/modules/ai/ai.service';
import { AuditService } from './../src/modules/audit/audit.service';
import { AuditInterceptor } from './../src/modules/audit/interceptors/audit.interceptor';
import * as fs from 'fs';
import * as path from 'path';

describe('AppController (E2E) - Comprehensive', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let accessToken: string;
  let userId: string;
  let pegawaiId: string;
  let reportId: string;

  // Mock AI Service agar tidak memanggil API eksternal (menghemat biaya & waktu)
  const mockAiService = {
    generateReport: jest.fn().mockResolvedValue({
      success: true,
      content: '# Mock Content\n\nGenerated by E2E Test.',
      tokensUsed: 50,
      model: 'gemini',
    }),
    getAvailableModels: jest.fn().mockReturnValue(['gemini', 'gpt']),
  };

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(AiService)
      .useValue(mockAiService)
      .compile();

    app = moduleFixture.createNestApplication();

    // Setup Aplikasi sama seperti main.ts
    app.setGlobalPrefix('api');
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        transform: true,
        forbidNonWhitelisted: true,
      }),
    );

    // Setup Audit Interceptor Manual
    const auditService = app.get(AuditService);
    const reflector = app.get(Reflector);
    app.useGlobalInterceptors(new AuditInterceptor(auditService, reflector));

    await app.init();

    prisma = app.get(PrismaService);

    // CLEANUP DATABASE SEBELUM TEST
    if (process.env.NODE_ENV !== 'production') {
      await prisma.auditLog.deleteMany();
      await prisma.notification.deleteMany();
      await prisma.fileUpload.deleteMany();
      await prisma.report.deleteMany();
      await prisma.akademikData.deleteMany();
      await prisma.pegawai.deleteMany();
      await prisma.user.deleteMany();
      await prisma.instansi.deleteMany();
    }

    // SEED DATA INSTANSI WAJIB
    await prisma.instansi.create({
      data: {
        header1: 'KEMENTERIAN TESTING',
        header2: 'KANTOR E2E',
        header3: 'UNIT TESTING INDONESIA',
        alamat: 'Jl. Test Driven Development No. 1',
        namaKepala: 'Kepala Test',
        nipKepala: '199001012020011001',
        pangkatKepala: 'Pembina/IV-a',
        titimangsa: 'Jakarta',
        isActive: true,
      },
    });
  });

  afterAll(async () => {
    await app.close();
  });

  // ========================================================================
  // 1. AUTHENTICATION TESTS
  // ========================================================================
  describe('Auth Module', () => {
    const userData = {
      email: 'user_e2e@example.com',
      password: 'Password123!',
      name: 'E2E User',
      role: 'ADMIN', // Set admin agar bisa akses semua route
    };

    it('POST /auth/register - Should register new user', async () => {
      const res = await request(app.getHttpServer())
        .post('/api/auth/register')
        .send(userData)
        .expect(201);

      expect(res.body.user.email).toBe(userData.email);
      expect(res.body.accessToken).toBeDefined();
      userId = res.body.user.id;
    });

    it('POST /auth/register - Should fail on duplicate email', () => {
      return request(app.getHttpServer()).post('/api/auth/register').send(userData).expect(400); // Bad Request
    });

    it('POST /auth/login - Should fail with wrong password', () => {
      return request(app.getHttpServer())
        .post('/api/auth/login')
        .send({
          email: userData.email,
          password: 'WrongPassword!',
        })
        .expect(401);
    });

    it('POST /auth/login - Should login successfully', async () => {
      const res = await request(app.getHttpServer())
        .post('/api/auth/login')
        .send({
          email: userData.email,
          password: userData.password,
        })
        .expect(200);

      expect(res.body.accessToken).toBeDefined();
      accessToken = res.body.accessToken;
    });

    it('GET /auth/me - Should get profile with token', () => {
      return request(app.getHttpServer())
        .get('/api/auth/me')
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.id).toBe(userId);
        });
    });
  });

  // ========================================================================
  // 2. PEGAWAI TESTS
  // ========================================================================
  describe('Pegawai Module', () => {
    const pegawaiData = {
      nip: '198501012010011005',
      nama: 'Budi E2E',
      jabatan: 'Guru Ahli Pertama',
      unitKerja: 'MTs E2E',
      jenisPegawai: 'PNS',
      gender: 'L',
      statusPegawai: 'AKTIF',
      email: 'budi@example.com',
    };

    it('POST /pegawai - Should create pegawai profile', async () => {
      const res = await request(app.getHttpServer())
        .post('/api/pegawai')
        .set('Authorization', `Bearer ${accessToken}`)
        .send(pegawaiData)
        .expect(201);

      expect(res.body.nip).toBe(pegawaiData.nip);
      pegawaiId = res.body.id;
    });

    it('POST /pegawai - Should fail if user already has pegawai data', () => {
      return request(app.getHttpServer())
        .post('/api/pegawai')
        .set('Authorization', `Bearer ${accessToken}`)
        .send({ ...pegawaiData, nip: '999999999999999999' })
        .expect(400);
    });

    it('GET /pegawai/me - Should return my data', () => {
      return request(app.getHttpServer())
        .get('/api/pegawai/me')
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.nama).toBe(pegawaiData.nama);
        });
    });
  });

  // ========================================================================
  // 3. INSTANSI TESTS
  // ========================================================================
  describe('Instansi Module', () => {
    it('GET /instansi - Should list instansi', () => {
      return request(app.getHttpServer())
        .get('/api/instansi')
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.data).toHaveLength(1);
          expect(res.body.data[0].header1).toBe('KEMENTERIAN TESTING');
        });
    });
  });

  // ========================================================================
  // 4. REPORTS & AI TESTS
  // ========================================================================
  describe('Reports Module', () => {
    const reportPayload = {
      modelAI: 'gemini',
      bulan: 1,
      tahun: 2025,
      tugasPokok: 'Melaksanakan pembelajaran E2E',
      tugasTambahan: 'Wali Kelas',
      targetTahunan: 'Lulus 100%',
      hambatan: 'Server lambat',
      solusi: 'Upgrade server',
      tokenLimit: 1000,
    };

    it('POST /reports/generate - Should generate report using Mock AI', async () => {
      const res = await request(app.getHttpServer())
        .post('/api/reports/generate')
        .set('Authorization', `Bearer ${accessToken}`)
        .send(reportPayload)
        .expect(201);

      expect(res.body.content).toContain('Mock Content');
      expect(res.body.status).toBe('DRAFT');
      expect(res.body.bulan).toBe(1);
      reportId = res.body.id;
    });

    it('POST /reports/generate - Should fail on Duplicate Period', () => {
      return request(app.getHttpServer())
        .post('/api/reports/generate')
        .set('Authorization', `Bearer ${accessToken}`)
        .send(reportPayload)
        .expect(400) // Expect Bad Request (Already exists)
        .expect((res) => {
          expect(res.body.message).toContain('sudah ada');
        });
    });

    it('GET /reports/:id - Should get detail', () => {
      return request(app.getHttpServer())
        .get(`/api/reports/${reportId}`)
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.id).toBe(reportId);
        });
    });

    it('PATCH /reports/:id - Should update draft', () => {
      return request(app.getHttpServer())
        .patch(`/api/reports/${reportId}`)
        .set('Authorization', `Bearer ${accessToken}`)
        .send({
          content: 'Updated Content Manual',
          tugasPokok: 'Updated Tugas',
        })
        .expect(200)
        .expect((res) => {
          expect(res.body.tugasPokok).toBe('Updated Tugas');
        });
    });

    it('POST /reports/:id/submit - Should submit report', () => {
      return request(app.getHttpServer())
        .post(`/api/reports/${reportId}/submit`)
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.status).toBe('SUBMITTED');
        });
    });

    it('GET /reports/:id/export/pdf - Should export PDF', () => {
      return request(app.getHttpServer())
        .get(`/api/reports/${reportId}/export/pdf`)
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect('Content-Type', 'application/pdf');
    });
  });

  // ========================================================================
  // 5. FILES TESTS (MOCK UPLOAD)
  // ========================================================================
  describe('Files Module', () => {
    const tempFilePath = path.join(__dirname, 'temp-e2e-file.txt');

    beforeAll(() => {
      fs.writeFileSync(tempFilePath, 'E2E Test File Content');
    });

    afterAll(() => {
      if (fs.existsSync(tempFilePath)) {
        fs.unlinkSync(tempFilePath);
      }
    });

    it('POST /files/upload - Should upload file', async () => {
      // Pastikan folder uploads ada (karena multer butuh)
      if (!fs.existsSync('./uploads')) {
        fs.mkdirSync('./uploads');
      }

      const res = await request(app.getHttpServer())
        .post('/api/files/upload')
        .set('Authorization', `Bearer ${accessToken}`)
        .attach('file', tempFilePath)
        .field('category', 'DOKUMEN')
        .expect(201);

      expect(res.body.originalName).toBe('temp-e2e-file.txt');

      // Cleanup file yang terupload di folder uploads
      if (res.body.path && fs.existsSync(res.body.path)) {
        fs.unlinkSync(res.body.path);
      }
    });
  });

  // ========================================================================
  // 6. NOTIFICATION & AUDIT TESTS
  // ========================================================================
  describe('Audit & Notification', () => {
    it('GET /audit - Should have logged activities', async () => {
      // Beri jeda sedikit agar async audit tersimpan
      await new Promise((resolve) => setTimeout(resolve, 1000));

      const res = await request(app.getHttpServer())
        .get('/api/audit')
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200);

      expect(res.body.data.length).toBeGreaterThan(0);

      // Cek apakah aksi SUBMIT tadi tercatat
      const submitLog = res.body.data.find((log) => log.action === 'SUBMIT');
      expect(submitLog).toBeDefined();
    });

    // Karena di laporan submit belum ada trigger otomatis buat notifikasi (biasanya di service),
    // kita tes manual endpoint notifikasi saja.
    it('GET /notifications - Should be empty initially', () => {
      return request(app.getHttpServer())
        .get('/api/notifications')
        .set('Authorization', `Bearer ${accessToken}`)
        .expect(200)
        .expect((res) => {
          expect(res.body.data).toBeDefined();
        });
    });
  });
});
